AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
  - 'test/date_sigil_test.rb'
  - 'test/number_sigil_test.rb'
  - 'test/uri_sigil_test.rb'
  - 'vendor/**/*'

Style/FormatStringToken:
  Enabled: false
